_target_: experiments.amplitudes.wrappers.AmplitudeDSIWrapper

net:
  _target_: experiments.baselines.dsi.DSI

  use_deepset: true
  hidden_channels_prenet: 384
  hidden_layers_prenet: 2
  out_dim_prenet_sep: 32
  hidden_channels_net: 384
  hidden_layers_net: 2
