_target_: experiments.amplitudes.wrappers.AmplitudeGAMLPWrapper

net:
 _target_: gatr.nets.GAMLP

 in_mv_channels: 4
 out_mv_channels: 1
 hidden_mv_channels: 4

 in_s_channels: 1
 out_s_channels: 1
 hidden_s_channels: 16

 num_blocks: 4
 dropout_prob: null

defaults:
 - /base_mlp@net.mlp