_target_: experiments.eventgen.wrappers.GATrCFM
beam_reference: spacelike
two_beams: false
add_time_reference: false
scalar_dims: [0]

net:
 _target_: gatr.nets.GATr

 in_mv_channels: 1
 out_mv_channels: 1
 hidden_mv_channels: 4

 in_s_channels: null
 out_s_channels: 4
 hidden_s_channels: 8

 num_blocks: 1
 reinsert_mv_channels: null
 reinsert_s_channels: null
 dropout_prob: null

 attention:
  num_heads: 2
  multi_query: false
  increase_hidden_channels: 2

defaults:
 - /base_attention@net.attention
 - /base_mlp@net.mlp
